---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 10.20.10.185-10.20.10.199
  METALLB_K8S_GATEWAY_ADDR: 10.20.10.185
  METALLB_TRAEFIK_ADDR: 10.20.10.186
